### ISSUE TITLE
[Feature] 깃허브 토큰 500에러를 400대로 변경

### ISSUE THREAD

**Issue by Skyrich2000** [42-world/42world-Backend#100]
## 작업할 내용
깃허브 토큰을 중복으로 로그인 시도시 500에러로 처리하고 있는 로직을
저희가 에러를 인지하고있기 때문에, 적절한 에러코드로 변경하면 좋을거같습니다.
403으로 처리하는건 어떨가요? @rockpell @blingblin-g 

## 해야할 일
- [ ] 로그인 토큰 에러만 잡기
- [ ] 해당 에러는 적절한 에러코드로 변환

**Comment by rockpell** [comment]
좋습니다
