### ISSUE TITLE
[Feature] logging 더 자세하게 나오는걸로 수정

### ISSUE THREAD

**Issue by Skyrich2000** [42-world/42world-Backend#108]
## 작업할 내용
멘토링 받고 이쁜 양식으로 변경

## 해야할 일
- [ ] 로깅 수정

**Comment by mimseong** [comment]
성민 받아가겠습니다

## 할 일
- 로깅 어떤 툴을 사용하는지 알아보기
- 어떤 부분을 로그 남길지 정하기
- 로그 실제로 남기기
