### ISSUE TITLE
[Feature] Slow Query에 대한 로깅

### ISSUE THREAD

**Issue by blingblin-g** [42-world/42world-Backend#119]
## 작업할 내용
<img width="358" alt="스크린샷 2022-02-19 오전 10 58 47" src="https://user-images.githubusercontent.com/60090391/154781704-37b054c7-9e2b-483d-a682-177564e6c366.png">

## 해야할 일
- [x] 1초 이상 걸리는 쿼리에 대해 로깅을 합니다.

**Comment by rockpell** [comment]
적용하였습니다
