### ISSUE TITLE
[Bug] 서초 체크인 값이 0 이 되는 오류

### ISSUE THREAD

**Issue by Skyrich2000** [42-world/42world-Backend#134]
## 오류 사진 및 설명
<img width="222" alt="image" src="https://user-images.githubusercontent.com/46391729/158008162-470260ad-6ef1-46cd-a877-463d3da18d62.png">

## 발생 위치
체크인 서비스 값 가져올때, 서초 클러스터는 데이터가 제대로 안들어오네요

**Comment by rockpell** [comment]
이거 오타 서초가 오타 나있어서 값이 0으로 나오고 있었네요
버그 수정하겠습니다
