### ISSUE TITLE
[Feature] 게시글/댓글 query 최적화

### ISSUE THREAD

**Issue by Skyrich2000** [42-world/42world-Backend#149]
## 작업할 내용
게시글, 댓글 likecount 증감 하는부분에서, 기존에 save로 되어있는 코드를, 레파지토리로 빼고 raw query를 적용합니다.
증감 레파지토리/서비스 함수는 반환값을 void로 해도 될거같습니다.
로직적으로 +1, -1 적용

**Comment by Yaminyam** [comment]
<img width="561" alt="image" src="https://user-images.githubusercontent.com/31057849/163955450-b24ef2fe-3b07-431e-807e-71b7aac18ec0.png">
이미 적용이 되어있는것 같은데 다른건가요??

**Comment by Yaminyam** [comment]
아 게시글에만 적용이 되어있고 댓글에는 적용이 안되어있군요 또르륵...ㅠ

**Comment by Skyrich2000** [comment]
제가 그떄 게시글에만 적용하고 아직 댓글에는 적용되어있지 않습니다.

**Comment by Yaminyam** [comment]
댓글도 수정하도록 하겠습니다~

**Comment by Yaminyam** [comment]
https://github.com/typeorm/typeorm/issues/3772
관련이슈가 존재하는군요

**Comment by Yaminyam** [comment]
@Skyrich2000 해당이슈에 나와있는 해결법으로 보니 save가 아닌 update함수를 이용하면 되는것 같은데 raw query를 사용하는것보단 typeorm 함수를 이용하는게 좋지 않을까요??

**Comment by Skyrich2000** [comment]
와우 이런 이슈는 어떻게 찾으신건가요 ㄸ 항상 대단하십니다
확실히 update 를 사용하는것으로 리펙토링 하면 좋을거같네요

**Comment by Yaminyam** [comment]
https://typeorm.io/repository-api
increment, decrement도 자체적인 함수로 제공하고있네요

**Comment by Skyrich2000** [comment]
```
await repository.increment({ firstName: "Timber" }, "age", 3)
```

**Comment by Yaminyam** [comment]
> ```
> await repository.increment({ firstName: "Timber" }, "age", 3)
> ```
> 
> 이런식으로 쓴다고 나와있네요 좋은정보 감사합니다. 저도 ORM 최대한 활용하는편이 좋다고 생각했어요

그런데 뭔가 변경하는 속성값이 string으로 들어가야하고 where 조건도 넣어줘야해서 다른분들 코드보니까 그냥 update로 많이쓰시는것 같네요
코드가 더러워지는듯 ㅡ,ㅡ

**Comment by Skyrich2000** [comment]
오 이슈에 정리가 엄청 잘 되어있네요

```
const post = await repository.findOneById(1);
post.counter++;
await repository.save(post);
```
지금 저희가 이렇게 되어있는데 이런식으로 save를 쓰는것은 엄청 느리고다고 되어있네요

```
const post = await repository.findOneById(id);
await repository.update(id, { counter: post.counter + 1 });
```
대신에, update를 

```
await repository.update(id, { counter: () => 'counter + 1' });
```

update 도 그냥 안쓰고 이런식으로 쓴다고 하네요?

**Comment by Yaminyam** [comment]
제가 영어를 잘못해서 이해를 정확히 한건 아니지만 유추해보자면 post에 있는 counter값을 사용하면 큐잉으로 인해 실제 db값이랑 차이가 날 경우에 문제가 생긴다는 뉘앙스로 이해가되네요
왜 arrow function으로 쓰는진 모르겠네요 ?!

**Comment by Skyrich2000** [comment]
저도 이슈 이해한대로 위의 커멘트 수정해봤습니다.
arrow function을 쓰는 이유는 좀더 찾아보겠습니다.

**Comment by Yaminyam** [comment]
방금 작업하다가 알게됐는데 주의할 점이 하나있네요
앞의 속성값은 dto에 정의되어있는 속성이름으로 작성해야하고
뒤의 문자열로 처리된 부분은 실제 db값을 참조하기 때문에 db의 속성값을 기준으로 작성해야합니다

**Comment by Skyrich2000** [comment]
> 뒤의 문자열로 처리된 부분은 실제 db값을 참조하기 때문에 db의 속성값을 기준으로 작성해야합니다

뒤의 문자열이 update 함수에서 'counter + 1' 같은 부분을 말씀하시는건가요?

**Comment by Yaminyam** [comment]
> > 뒤의 문자열로 처리된 부분은 실제 db값을 참조하기 때문에 db의 속성값을 기준으로 작성해야합니다
> 
> 뒤의 문자열이 update 함수에서 'counter + 1' 같은 부분을 말씀하시는건가요?

맞습니다! 저희서비스 같은 경우에 db와 dto의 네이밍 컨벤션이 달라 앞은 viewCount 뒤는 view_count와 같은 식으로 작성해야합니다

**Comment by Skyrich2000** [comment]
아 그렇네요 QueryBuilder 쓸때도 이부분 조심해야하더라구요 ㅋㅋㅋ
