### ISSUE TITLE
[Feature] 테스트 파일 이름 *.e2e.spec.ts 로 변경

### ISSUE THREAD

**Issue by Skyrich2000** [42-world/42world-Backend#161]
## 작업할 내용
기존의 테스트 파일 이름을 *.e2e-spec.ts 에서 *.e2e.spec.ts 로 변경

다른 익스텐션에서 호환이 잘 안됩니다.

**Comment by Yaminyam** [comment]
github에 관련키워드로 검색해보면
https://github.com/search?p=1&q=e2e.spec.ts&type=Code
e2e-spec.ts로 명시된경우가 더 많아보이는데 어떤 익스텐션에서 호환성 문제가 존재하는건가요??
그리고 신기하게 e2e.spec.ts로 검색했는데 e2e-spec.ts와 e2e.spec.ts가 둘다 검색되네요

**Comment by Skyrich2000** [comment]
흠.. vscode jest extension 이 뭔가 *.e2e-spec.ts을 인식못하는거같아서 바꾸자는거였는데, 좀더 시도해보겠습니다.
그리고 vscode 테마 아이콘도 e2e-spec.ts 파일은 테스트 파일로 인식안하더라구요

**Comment by Yaminyam** [comment]
<img width="249" alt="image" src="https://user-images.githubusercontent.com/31057849/163504999-b634f735-d594-45a8-a903-0eb725e4be55.png">
vscode icon 확장 사용중입니다
e2e-spec이랑 e2e.spec이랑 둘 다 인식되네요!
<img width="271" alt="image" src="https://user-images.githubusercontent.com/31057849/163505075-4443a092-b565-4c13-b2f0-fe053d979e8b.png">
추가로 material icon theme 확장도 동일하게 인식하는거로 확인했습니다

**Comment by Skyrich2000** [comment]
머야 내 테마만 이상한거였어 🥲

**Comment by Yaminyam** [comment]
테마 어떤거 쓰시나요??
그리고 jest 확장은 다운받아봤는데 어떻게 사용하는건질 모르겠네요

**Comment by Skyrich2000** [comment]
<img width="196" alt="image" src="https://user-images.githubusercontent.com/46391729/163547509-41d7be30-66ab-4600-adf3-61e123d14fe3.png">

저도 material icon theme 확장 쓰고있는데 왜이러는걸까요... 

jest 확장쓰면 일일이 cli에서 테스트 안돌리고 에디터 환경에서 테스트 하나씩 돌려볼수있어요
아직 unit test 가 없어서 괜찮긴한데, unit test 붙으면 함수 하나 테스트하고싶은데 cli에서 파일 전체를 계속 테스트해야하는 번거로움이 있을까봐 바꾸려고 했던거였어요
지금보니 어자피 unit test 에서 그냥 파일이름을 *.spec.ts 로 하면 되니까 지금 e2e 이름을 바꿀필요는 없을거같긴하네요

**Comment by Yaminyam** [comment]
저 주황색은 테스트로 인식이 된게 아니라 변경된파일이라 주황색으로 변한것같구 e2e.spec이랑 e2e-spec을 둘 다 인식 못하는것 같은데요...?

**Comment by Skyrich2000** [comment]
음...? 어 머야 진짜네 지금까지 해골물 아이콘 쓰고있었음 ㅋㅋㅋㅋㅋ

**Comment by Yaminyam** [comment]
ㅋㅋㅋㅋ 주황색은 git에서 modify된걸 알려주는거로 알고있습니다

**Comment by Skyrich2000** [comment]
파일 확장자는 e2e-spec 으로 냅두고, 이슈 닫겠습니다.
