### ISSUE TITLE
[Docs] readme 실행하기와 테스트실행하기 형식 다름

### ISSUE THREAD

**Issue by Yaminyam** [42-world/42world-Backend#186]
## 작업할 내용
<img width="888" alt="image" src="https://user-images.githubusercontent.com/31057849/163705510-eaeba41e-dc09-4509-b1b0-e333433a462e.png">

둘이 거의 유사한 내용인데 하나는 점으로 나열되어있고 하나는 없어서 실행하기도 점을 지우는게 좋아보입니다.

**Comment by Skyrich2000** [comment]
ㅋㅋㅋ 그러게요 조금 불편하네요
