### ISSUE TITLE
[Bug] 게시글 요청 API 작동 오류

### ISSUE THREAD

**Issue by PIut0** [42-world/42world-Backend#212]
## 오류 사진 및 설명
게시글 리스트를 요청할때 categoryID, page, take(가져올 게시글 갯수) 를 parameter 로 해서 요청하는데,
게시판의 n번째 page 에서 m 개의 게시글을 가져오지 못할경우 500 이 응답되며 게시글을 받아올 수 없습니다.

예를들어 자유게시판에 총 게시물이 13개이고, 1페이지당 5개의 게시글을 가져온다 하면
첫번째와 두번째 페이지에선 5개씩 잘 가져와지나 세번째 페이지에선 3개밖에 가져오지 못해서 500이 리턴되는것 같습니다.

에러가 발생한 API url 도 첨부드립니다.
Url: http://api-alpha.42world.kr:8888/articles?categoryId=1&page=3&take=5

**Comment by Yaminyam** [comment]
@PIut0 
현재 배포된 버전의 e2e테스트가 게시글을 1,2개정도 삽입하고 10개씩 불러오록 호출해서 테스트를 진행하는데 문제가 없었는데 다른 오류가 있는것 같습니다
첨부해주신 url로 접속해보니 unauthrized 를 받아서 회원가입을 진행하려고보니 42이메일 인증도 401이 뜨는군요 ㅠ

**Comment by PIut0** [comment]
저도 지금 live 서버 확인해보니 alpha 서버에서만 문제를 일으키는것 같네요.. 일단 확인만 해두겠습니다

**Comment by Skyrich2000** [comment]
alpha 서버의 일시적 오류였습니다. alpha 서버 지금은 정상작동합니다.
