### ISSUE TITLE
[Bug] batch server 띄우기

### ISSUE THREAD

**Issue by Yaminyam** [42-world/42world-Backend#232]
## 오류 사진 및 설명
![image](https://user-images.githubusercontent.com/31057849/167905756-b8b5bc55-569b-4d22-8034-61088db364cf.png)

## 발생 위치
메인화면 체크인 서비스

## 해결시도
hotfix로 batch server docker로 추가로 띄우도록 작업

**Comment by Skyrich2000** [comment]
swarm으로 작업완료!
