### ISSUE TITLE
[Bug] 쿠키 옵션 보안 챙기기

### ISSUE THREAD

**Issue by rockpell** [42-world/42world-Backend#235]
## 오류 사진 및 설명
- 지금 쿠키 발급 옵션을 `sameSite: 'none'`을 사용하고 있어서 쿠키가 잘 발급되는지 확인 후 `lax`로 설정해야합니다
- httpOnly 설정이 없어서 추가해야합니다

**Comment by Yaminyam** [comment]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/31057849/168765969-9463c8f0-c883-4705-bc87-1c2aec2970b6.png">
하위 도메인의 같은 사이트로 취급되는데 일전에 작업때 왜 발급이 안된지는 테스트를 해봐야겠네요

**Comment by Yaminyam** [comment]
secure 옵션은 해당쿠키를 https에서만 사용가능하도록 하는 옵션으로 중간에 쿠키를 탈취하더라도 https로 전송될경우 암호화되어있어 해당 내용을 알 수 없지만 유저의 브라우저 단위에서 사용한다면 secure옵션이더라도 해당 쿠키가 사용 가능합니다
