### ISSUE TITLE
[Bug] 페이지 로그인 이후 로그아웃

### ISSUE THREAD

**Issue by leewoooo** [42-world/42world-Backend#250]
## 오류 사진 및 설명
![image](https://user-images.githubusercontent.com/74294325/171777781-c42eb51c-b3a6-4aec-8c53-157a029f6c89.png)

## 발생 위치

구경하던 도중 로그인 후 로그아웃을 하게되면 403을 받아 로그아웃이 되지 않네요

**Comment by Yaminyam** [comment]
방금 제 환경에서 테스트해본결과 정상적으로 로그아웃되었습니다
다른 조건이 인증이 안된 상황에서의 로그아웃인것 같은데 확인해보도록 하겠습니다

**Comment by Skyrich2000** [comment]
관심 가져주셔서 감사합니다! 코드를 보니까 실제로 로그아웃부분은 권한을 잘못 설정해뒀었네요 😮
#251 에서 수정했습니다. 오늘밤에 배포 하도록 하겠습니다! 감사합니다 😃

**Comment by leewoooo** [comment]
@Skyrich2000 그럼 배포 이후 이슈는 닫아주시면 감사하겠습니다 :)
