### ISSUE TITLE
[Feature] 정상동작 확인 action 추가

### ISSUE THREAD

**Issue by Yaminyam** [42-world/42world-Backend#265]
## 작업할 내용
batch, api, admin 각 정상실행 확인 action workflow 추가

## 해야할 일
- [ ] todo1
- [ ] todo2
- [ ] todo3

**Comment by Skyrich2000** [comment]
yarn lint 이나, yarn prettier 같이 확인해서 lint 에 문제 없는지도 같이 확인하면 좋을거같습니다.

e2e 테스트 돌릴떄 병렬로 돌려서 확인하게 해도 괜찮을거같긴하네요

**Comment by Skyrich2000** [comment]
> yarn lint 이나, yarn prettier 같이 확인해서 lint 에 문제 없는지도 같이 확인하면 좋을거같습니다.
> 
> e2e 테스트 돌릴떄 병렬로 돌려서 확인하게 해도 괜찮을거같긴하네요

lint 는 Codacy가 확인해주는것같으니, 따로 action을 구성하지 않아도 될거같네요

**Comment by Skyrich2000** [comment]
main.ts 이외에는 e2e 테스트로 안잡히는일은 거의 없기때문에 별도로 확인하는 action을 두지는 않는걸로 하겠습니다!
