### ISSUE TITLE
[Feature] skip ci tag

### ISSUE THREAD

**Issue by Yaminyam** [42-world/42world-Backend#302]
## 작업할 내용
ci 가 작동할 필요가 없는 문서작업이나 간단한 작업의 경우 또는 강제로 머지해야하는 경우 설정에서 required ci를 수정하는 식으로 사용하였으나 skip ci tag를 만들어서 관리
예시 : https://github.com/lablup/backend.ai/pull/651

**Comment by Skyrich2000** [comment]
이거 아마 깃허브 내장일걸요 지금도 될듯??

**Comment by Yaminyam** [comment]
띠용 고렇구만요

**Comment by Skyrich2000** [comment]
한번 테스트 해보시죠

**Comment by Yaminyam** [comment]
저희 라벨에 아예 skip ci 라는친구가 없네요
