### ISSUE TITLE
[Bug] 캐릭터 변경이 불가능합니다

### ISSUE THREAD

**Issue by mimseong** [42-world/42world-Backend#304]
## 오류 사진 및 설명
![image](https://user-images.githubusercontent.com/50068946/185773068-b2d9a754-a3ef-440f-a74a-f19d013e44f2.png)

![image](https://user-images.githubusercontent.com/50068946/185773071-d6315f4b-3018-4634-b81e-3100aa9eda3b.png)

## 발생 위치

https://www.42world.kr/mypage

마이페이지에서 마지막 고양이로 사진 변경을 하면 에러가 납니다. 

## 해결시도

해결해주세요

**Comment by Yaminyam** [comment]
maybe this issue resolved by #301

**Comment by mimseong** [comment]
네엡 확인했습니다
