### ISSUE TITLE
[Feature] 42인증이 되어있지 않아도, 닉네임은 열람 가능해야함

### ISSUE THREAD

**Issue by Skyrich2000** [42-world/42world-Backend#53]
## 작업할 내용
깃허브 인증만 되어있고, 42인증이 되어있지 않은 경우 
인증하기 페이지에서 깃허브 닉네임 조차 보이지 않습니다...
Novice를 위한 전용 Profile 확인페이지가 필요할거같은데,
어떻게 해야할지 고민이네요

뭔가 이런식으로 되어야할거같습니다.
* GET /users/me 
  * Cadet 만 접근가능
* GET /users/profile
  * Cadet, Novice 모두 접근 가능
  * 닉네임, 캐릭터만 포함

또는, 프론트쪽에서 아예 정보를 표시하지 않는 방향으로 기획을 수정하는 방안도 검토해볼만한거같습니다.

**Comment by rockpell** [comment]
본인 정보는 권한이랑 무관하게 보여줘도 괜찮지 않을까요

**Comment by Skyrich2000** [comment]
그러면 위에 써놓은대로 api를 수정해보겠습니다.
권한 관련 부분도 손을 한번 쭉 봐야겠네요
