### ISSUE TITLE
[Bug] 배포 환경에서의 조회수 관련

### ISSUE THREAD

**Issue by blingblin-g** [42-world/42world-Backend#78]
## 오류 사진 및 설명
로컬에서는 괜찮은데 배포 환경에서만 조회수가 (가끔!) 두배가 되는 현상
천천히 하면 괜찮은데 빠르게 여러번 하면 조회수가 2개씩 오름

## 발생 위치
게시글 디테일

## 해결시도
- 로컬에서는 잘 됨
- 천천히 하면 잘 됨

## 추가 작업
- 프론트에서도 변경이 필요할듯 함 (수정 시에 api 두번 쏘는 부분)

**Comment by Skyrich2000** [comment]
프론트에서 문제 해결하였습니다.
