### ISSUE TITLE
[Feature] 익명 게시판 생성

### ISSUE THREAD

**Issue by blingblin-g** [42-world/42world-Backend#85]
## 해야할 일
- [ ] response에서 닉네임을 다 가려서 내려야 함
- [ ] 익명 게시판에서 다른 api를 쏘도록 할지, category가 뭐냐에 따라 익명처리를 할지
- [x] 게시판 타입 설정 및 그에 따른 권한 정의

**Comment by Skyrich2000** [comment]
현재 본인이 쓴 게시글인지 아닌지 확인하는 방법이 프론트에 저장되어있는 user id 로 비교해서 구하고 있습니다.

다만, 익명 게시판은 유저를 노출하지 않게 하기 위해서, user id 조차 넘겨주지 않기 때문에 프론트에서 본인이 쓴글인지 비교할수가 없습니다.
본인이 쓴글인지 아닌지를 백엔드단에서 비교해줘야할거같네요..

**Comment by Skyrich2000** [comment]
[] 문서화
